#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

def configure(conf):
	conf.env.LIB_BOOST      = ['boost_program_options', 'boost_system', 'boost_system', 'boost_log', 'boost_log_setup', 'pthread']
#	conf.env.LIB_LOG4CPP    = ['log4cpp']
	conf.env.LIB_UDNS		= ['udns']
	conf.env.LIBPATH_BOOST   = ['/home/nbryskin/source/boost_1_43_0/stage/lib']
#	conf.env.LINKFLAGS_TEST = ['-g']
#	conf.env.CPPPATH_TEST   = ['/opt/gnome/include']

def build(bld):
	# 1. A simple c++ program
	bld(
		features = 'cxx cprogram',
		source = 'fastproxy.cpp channel.cpp session.cpp resolver.cpp proxy.cpp',
		target = 'fastproxy',
		defines = ['BOOST_ASIO_DISABLE_THREADS', 'BOOST_LOG_NO_THREADS'],
		uselib = 'BOOST UDNS',
		cxxflags = '-std=c++0x')
