#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
	conf.env.LIB_BOOST      = ['boost_program_options', 'boost_system', 'boost_log', 'boost_log_setup', 'pthread', 'boost_filesystem']
	conf.env.LIB_UDNS       = ['udns']
	conf.env.LIB_RT         = ['rt']
	conf.env.LIBPATH_BOOST  = ['/usr/local/lib64']

def build(bld):
	# 1. A simple c++ program
	bld(
		features = 'cxx cprogram',
		source = 'fastproxy.cpp channel.cpp session.cpp resolver.cpp proxy.cpp statistics.cpp stat_sess.cpp signal.cpp',
		target = 'fastproxy',
		defines = ['BOOST_ASIO_DISABLE_THREADS', 'BOOST_LOG_NO_THREADS'],
		uselib = 'BOOST UDNS RT',
		cxxflags = '-std=c++0x')
	bld.install_dir('/var/log/fastproxy')
